rate: 10.0
flight_duration: 60.0
num_agents: 4
log_data: True

 
takeoff_target_height: 1.0
takeoff_duration: 2.5
hover_duration: 2.0
land_duration: 2.5
land_target_height: 0.02
sleep_duration_before_shutdown: 4.0

# Casadi Parameters
nx: 2 # Number of states - \gamma and \dot{\gamma}
nu: 1 # Number of control inputs - \ddot{\gamma}
K: 20 # Prediction horizon
T: 1000 # Simulation time
h: 0.1 # Time step
u_min: [-15.0] 
u_max: [15.0]
x_min: [0.0, 0.0]
x_max_up: 2.0
du: 1.0 # Distance between agents for smoothing function

# Communcation term
du11: 1.0 # *
du12: 2.5

# Collision Avoidance
du21: 0.8 # *
du22: 0.125
du31: 0.25
du32: 0.125

# Pace keeping term
dupc: 0.9 # *


# Initial gammas
gamma_init:
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]
- [0.0, 1.0]

# Circular trajectories
radius: 
- 0.5
- 1.5
- 0.125
- 0.125
- 2.5
- 3.0
- 3.5
- 4.0
- 4.5
- 5.0



circle_center_coordiantes:
- [0.0, 0.5, 1.0]
- [0.0, -0.5, 1.0]
- [0.5, 0.0, 1.0]
- [-0.5, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.0, 0.0, 1.0]

init_angle: 
- 3.14
- 3.14
- -1.570795
- -1.570795
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0



angular_velocity:
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159

rotation_direction: # CW = 1, CCW = -1
- -1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1



# Trajectories with phaseshift - Yin-Yang
radius_1: 
- 1.0
- 0.5
- 0.5
- 1.0
- 0.5
- 0.5
- 1.0

circle_center_coordiantes_1:
- [0.0, 0.0, 1.0]
- [0.5, 0.0, 1.0]
- [-0.5, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.5, 0.0, 1.0]
- [-0.5, 0.0, 1.0]
- [0.0, 0.0, 1.0]


init_angle_1: 
- -1.570795
- 0.0
- 0.0
- 3.14159
- 0.0
- 0.0
- 3.14159

angular_velocity_1:
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159

rotation_direction_1: # CW = 1, CCW = -1
- 1
- 1
- -1
- 1
- 1
- -1
- 1

# End time for each trajectory in sequence
duration_1:
- 5
- 15
- 25
- 35
- 45
- 55
- 65


# Trajectories with phaseshift - Yin-Yang
radius_2: 
- 1.0
- 0.5
- 0.5
- 1.0
- 0.5
- 0.5
- 1.0

circle_center_coordiantes_2:
- [0.0, 0.0, 1.0]
- [0.5, 0.0, 1.0]
- [-0.5, 0.0, 1.0]
- [0.0, 0.0, 1.0]
- [0.5, 0.0, 1.0]
- [-0.5, 0.0, 1.0]
- [0.0, 0.0, 1.0]


init_angle_2: 
- 1.570795
- 0.0
- 0.0
- 3.14159
- 0.0
- 0.0
- 3.14159

angular_velocity_2:
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159
- 0.314159

rotation_direction_2: # CW = 1, CCW = -1
- -1
- 1
- -1
- -1
- 1
- -1
- -1

# End time for each trajectory in sequence
duration_2:
- 5
- 15
- 25
- 35
- 45
- 55
- 65